## @RequestMapping#headers

openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: "http://localhost:8080"
  description: Generated server url
paths:
  /rest/p2:
    get:
      tags:
      - my-rest-controller
      operationId: p2
      parameters:
      - name: h1
        in: header
        schema:
          type: string
          enum:
          - h1_value
      - name: h2
        in: header
        schema:
          type: string
          enum:
          - h2_value
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
