openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: "http://localhost:8080"
  description: Generated server url
paths:
  /rest2/p4/{mv1}/{mv2}:
    get:
      tags:
      - my-rest-controller-2
      operationId: p4
      parameters:
      - name: mv1p
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: mv2p
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /rest2/p3/{pvar11}/{pavr22}:
    get:
      tags:
      - my-rest-controller-2
      operationId: p3
      parameters:
      - name: pvar11
        in: path
        required: true
        schema:
          type: string
      - name: pavr22
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /rest2/p2/{pvar1}-{pavr2}:
    get:
      tags:
      - my-rest-controller-2
      operationId: p2
      parameters:
      - name: pvar1
        in: path
        required: true
        schema:
          type: string
      - name: pavr2
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /rest2/p1:
    get:
      tags:
      - my-rest-controller-2
      operationId: p1
      parameters:
      - name: coocoo
        in: cookie
        required: false
        schema:
          type: string
          default: foo
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /rest2/cook:
    get:
      tags:
      - my-rest-controller-2
      operationId: setCookie
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
