## default values for @RequestParam and @RequestHeader

openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: "http://localhost:8080"
  description: Generated server url
paths:
  /rest/p4:
    get:
      tags:
      - my-rest-controller
      operationId: p4
      parameters:
      - name: param1
        in: query
        required: false
        schema:
          type: string
          default: param1_value
      - name: myheader1
        in: header
        required: false
        schema:
          type: string
          default: header1_value
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
