## - RequestBody
## - RequestPart

openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: "http://localhost:8080"
  description: Generated server url
paths:
  /rest4/p2:
    post:
      tags:
      - example-controller
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                doc:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /rest4/p1:
    post:
      tags:
      - example-controller
      operationId: handle
      requestBody:
        content:
          application/json:
            schema:
              type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
