## RequestMapping with #produces and #consumes attributes:

openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: "http://localhost:8080"
  description: Generated server url
paths:
  /rest/p5:
    post:
      tags:
      - my-rest-controller
      operationId: p5
      requestBody:
        content:
          text/json:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            text/json:
              schema:
                type: string
components: {}
